#!/usr/bin/env bash
# A simple script for getting the changes in energy over an SCF from a Gaussian log file and plotting them in gnuplot. 
##
# A little too simple - doesn't handle Optimisations well, for example.

TempDir=/tmp/g09scfplot-$$
TempFile=g09scfdata-$$
mkdir $TempDir

# Normal SCF example:
: "
 E= -30597.5567313298     Delta-E=       -0.090354048400 Rises=F Damp=F
"

# QC example:
: "
 Iteration  55 EE= -30636.7408437426     Delta-E=       -0.022773469616 Grad=1.694D-01
"
grep 'Delta-E' $1 | sed -ne 's/^.*Delta-E=[ ]\+\([-]\?[0-9.]\+\) .*/\1/p' >$TempDir/$TempFile

# We use the abs(energy change) so that we can do log plots.
PlotInstructions=" set term x11;
set logscale y 10;
plot \"$TempDir/$TempFile\" using (abs(\$1)) with linespoints title \"Delta-E\"
"

echo $PlotInstructions | gnuplot -persist

rm $TempDir/$TempFile
rmdir $TempDir

