#!/usr/bin/env bash
# Creates a .tar.gz archive of a Turbomole calculation's key files. (The ones copied with the Turbomole script cpc.)
##

OLDDIR=`pwd`

#Get command line arguments
while getopts  "hd:" flag
do
    case "$flag" in
        "d")
			if [[ -d "$OPTARG" ]]; then
			  cd $OPTARG
			fi
			;;
		"h")
			echo "Usage: $0 [-d directory] "
			exit
			;;
        *)
            echo "Invalid argument specified." >&2
            return 1 
            ;;
    esac
done

DIRNAME=`pwd`
DIRNAME=${DIRNAME##*/}
TMPDIR=/tmp/tmarchive-$$
TMPCOPYDIR=$TMPDIR/$DIRNAME

mkdir -p $TMPCOPYDIR && cpc $TMPCOPYDIR && cd $TMPDIR && tar -czf $DIRNAME.tar.gz $DIRNAME && mv $DIRNAME.tar.gz $OLDDIR/ && rm -Rf $TMPDIR 


