#!/usr/bin/env bash
# Very simply changes the orbital shift and damping parameters of a Turbomole control file to better ones for open shell calculations.
##

echo Before:
grep -e '$scforbitalshift' -e '$scfdamp' control
sed -e 's/closedshell=/automatic=/' -e 's/scfdamp   start=0.700/scfdamp  start=3.5/' control > control.tmp && mv control.tmp control && echo Done.
echo After:
grep -e '$scforbitalshift' -e '$scfdamp' control



